# Generated by Django 5.0.6 on 2024-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0045_certificate_description_1_certificate_description_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('shifr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shifr')),
            ],
        ),
    ]
