# Generated by Django 5.0.6 on 2024-09-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0047_product_advantage_2_product_advantage_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
    ]
