# Generated by Django 5.0.6 on 2024-09-25 07:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0049_alter_localdocs_file_alter_product_date_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Ta'rif 2"),
        ),
    ]
