# Generated by Django 5.0.6 on 2024-09-25 09:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0052_alter_new_description_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Ta'rif 2"),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_3',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Ta'rif 3"),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_4',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Ta'rif 4"),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_5',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Ta'rif 5"),
        ),
    ]
